//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Movies
{
    using System;
    using System.Collections.Generic;
    
    public partial class movies
    {
        public int id { get; set; }
        public string name { get; set; }
        public string genre { get; set; }
        public string description { get; set; }
        public int rating { get; set; }
        public string director { get; set; }
        public string year { get; set; }
    }
}
